export const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';
export const FETCH_BEER_WITH_DELAY_REQUEST = 'FETCH_BEER_WITH_DELAY_REQUEST';
export const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
export const FETCH_BEER_FAILURE = 'FETCH_BEER_FAILURE';
export const BEER_LIST_INITIALIZE_REQUEST = 'BEER_LIST_INITIALIZE_REQUEST';
export const BEER_LIST_INITIALIZE_SUCCESS = 'BEER_LIST_INITIALIZE_SUCCESS';

export const FETCH_BEER_ITEM_REQUEST = 'FETCH_BEER_ITEM_REQUEST';
export const FETCH_BEER_ITEM_SUCCESS = 'FETCH_BEER_ITEM_SUCCESS';
export const FETCH_BEER_ITEM_FAILURE = 'FETCH_BEER_ITEM_FAILURE';

export const SET_PAGE = 'SET_PAGE';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const SET_NEXT_PAGE_AVAILABILITY = 'SET_NEXT_PAGE_AVAILABILITY';
export const GO_TO_NEXT_PAGE = 'GO_TO_NEXT_PAGE';

export const TOGGLE_INFINITE_SCROLL = 'TOGGLE_INFINITE_SCROLL';