export const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';
export const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
export const FETCH_BEER_FAILURE = 'FETCH_BEER_FAILURE';
export const BEER_LIST_INITIALIZE = 'BEER_LIST_INITIALIZE';

export const FETCH_BEER_ITEM_REQUEST = 'FETCH_BEER_ITEM_REQUEST';
export const FETCH_BEER_ITEM_SUCCESS = 'FETCH_BEER_ITEM_SUCCESS';
export const FETCH_BEER_ITEM_FAILURE = 'FETCH_BEER_ITEM_FAILURE';

export const SET_FETCH_BEER_TIMER = 'SET_FETCH_BEER_TIMER';
export const CLEAR_FETCH_BEER_TIMER = 'CLEAR_FETCH_BEER_TIMER';

export const SET_PAGE = 'SET_PAGE';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const SET_PAGINATION_AVAILABILITY = 'SET_PAGINATION_AVAILABILITY';

export const TOGGLE_INFINITE_SCROLL = 'TOGGLE_INFINITE_SCROLL';