export const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';
export const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
export const FETCH_BEER_FAILURE = 'FETCH_BEER_FAILURE';

export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
export const SET_MIN_ABV = 'SET_MIN_ABV';
export const SET_MAX_ABV = 'SET_MAX_ABV';

export const SET_PAGE = 'SET_PAGE';
export const SET_PAGINATOR_AVAILABILITY = 'SET_PAGINATOR_AVAILABILITY';